// SPDX-License-Identifier: AGPL-3.0-or-later

use std::fmt::Write;
use std::fs;
use std::path::Path;

type RingAtoms = Vec<(String, usize)>;
type SystemEntry = (String, String, RingAtoms);
type PdbAtomSerial = (String, u64);
type PdbResidue = (String, String, Vec<PdbAtomSerial>);
type PdbResidues = Vec<PdbResidue>;

/// Auto-generate `index_map.toml` by scanning data/ for .gro topology files.
/// When `entity_groups` is provided (from a domain profile), uses those definitions
/// for atom names and residue filters. Otherwise falls back to hardcoded carbohydrate defaults.
pub(super) fn auto_generate_index_map(
    data_root: &Path,
    entity_groups: Option<&[pseudospore_core::EntityGroup]>,
) -> Option<String> {
    let mut systems: Vec<SystemEntry> = Vec::new();

    // Resolve atom names and residue filters from profile or defaults
    let (atom_names, residue_filters): (Vec<String>, Vec<String>) =
        if let Some(groups) = entity_groups {
            if let Some(first) = groups.first() {
                (first.atoms.clone(), first.residue_filter.clone())
            } else {
                (default_atom_names(), default_residue_filters())
            }
        } else {
            (default_atom_names(), default_residue_filters())
        };

    // Walk data/ subdirectories looking for .gro files
    if let Ok(entries) = std::fs::read_dir(data_root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let module_name = entry.file_name().to_string_lossy().to_string();

            // Look for .gro files in this module
            if let Ok(files) = std::fs::read_dir(&path) {
                for file in files.flatten() {
                    let fpath = file.path();
                    if fpath.extension().is_some_and(|e| e == "gro")
                        && let Some(ring_atoms) =
                            extract_ring_atoms_from_gro(&fpath, &atom_names, &residue_filters)
                    {
                        let rosetta = format!(
                            "data/{}/{}",
                            module_name,
                            file.file_name().to_string_lossy()
                        );
                        systems.push((module_name.clone(), rosetta, ring_atoms));
                    }
                }
            }
        }
    }

    if systems.is_empty() {
        return None;
    }

    // Scan PDB files for ALL residue types (returns per-residue-type serial sets)
    let all_pdb_residues = scan_pdb_all_residues(data_root, &atom_names, &residue_filters);

    let mut output = String::new();
    output.push_str("# Auto-generated domain ↔ computation index mapping\n");
    output.push_str("# Generated by `litho emit-pseudospore`\n");
    if all_pdb_residues.is_empty() {
        output.push_str("# Review and correct domain indices manually if needed\n");
    } else {
        output.push_str("# Domain indices auto-extracted from PDB files in data/\n");
    }
    output.push_str("\n[meta]\n");
    output.push_str("ring_order = [\"C1\", \"C2\", \"C3\", \"C4\", \"C5\", \"O5\"]\n\n");

    for (module, rosetta, atoms) in &systems {
        // Select the appropriate PDB residue for this module:
        // "enzyme-bound" modules use BXYL (the -1 subsite ligand)
        // "free" modules or others use XYS/the first match
        let pdb_serials = select_pdb_serials_for_module(module, &all_pdb_residues);

        let _ = writeln!(output, "[systems.\"{module}\"]");
        let _ = writeln!(output, "description = \"Auto-detected from {rosetta}\"");
        let _ = writeln!(output, "rosetta_stone = \"{rosetta}\"\n");
        let _ = writeln!(output, "[systems.\"{module}\".ring]");

        for (name, idx) in atoms {
            let domain_val = pdb_serials
                .iter()
                .find(|(pdb_name, _)| pdb_name == name)
                .map_or_else(|| "\"?\"".to_string(), |(_, serial)| format!("{serial}"));

            let _ = writeln!(
                output,
                "{name} = {{ domain = {domain_val}, computation = {idx} }}"
            );
        }

        let note = if pdb_serials.is_empty() {
            "Domain indices need manual assignment from PDB source. Computation indices auto-extracted from topology."
        } else {
            "Domain = PDB HETATM serial (auto-extracted). Computation = GROMACS topology index (auto-extracted)."
        };
        let _ = writeln!(output, "\n[systems.\"{module}\"._note]");
        let _ = writeln!(output, "value = \"{note}\"\n");
    }

    Some(output)
}

/// Select the correct PDB serial set for a given module name.
/// "enzyme-bound" modules get BXYL serials; "free" modules get XYS; others get last match.
fn select_pdb_serials_for_module(module: &str, all_residues: &[PdbResidue]) -> Vec<PdbAtomSerial> {
    if all_residues.is_empty() {
        return Vec::new();
    }

    let module_lower = module.to_lowercase();

    if module_lower.contains("enzyme") || module_lower.contains("bound") {
        // Enzyme-bound: prefer BXYL, then last residue (likely the ligand at end of PDB)
        if let Some((_, _, atoms)) = all_residues.iter().find(|(rn, _, _)| rn == "BXYL") {
            return atoms.clone();
        }
        // Fallback to last residue (highest serials = end of PDB = ligand)
        return all_residues
            .last()
            .map(|(_, _, a)| a.clone())
            .unwrap_or_default();
    }

    if module_lower.contains("free") || module_lower.contains("xylose") {
        // Free xylose: prefer XYS, then first residue
        if let Some((_, _, atoms)) = all_residues.iter().find(|(rn, _, _)| rn == "XYS") {
            return atoms.clone();
        }
        return all_residues
            .first()
            .map(|(_, _, a)| a.clone())
            .unwrap_or_default();
    }

    // Default: use first residue found
    all_residues
        .first()
        .map(|(_, _, a)| a.clone())
        .unwrap_or_default()
}

/// Scan data/ for .pdb files and extract atom serials for ALL matching residues.
/// Returns a Vec of (`residue_name`, `residue_number`, atoms) for each found residue.
fn scan_pdb_all_residues(
    data_root: &Path,
    atom_names: &[String],
    residue_filters: &[String],
) -> PdbResidues {
    let ring_atom_names: Vec<&str> = atom_names.iter().map(std::string::String::as_str).collect();
    let sugar_residues: Vec<&str> = residue_filters
        .iter()
        .map(std::string::String::as_str)
        .collect();

    // Collect ALL sugar ring atom sets keyed by (res_name, res_num)
    let mut all_residues: PdbResidues = Vec::new();

    let search_dirs = [
        data_root.to_path_buf(),
        data_root.parent().unwrap_or(data_root).to_path_buf(),
    ];

    for search_dir in &search_dirs {
        if let Ok(entries) = fs::read_dir(search_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                let mut pdb_paths: Vec<std::path::PathBuf> = Vec::new();

                if path.is_dir() {
                    if let Ok(sub_entries) = fs::read_dir(&path) {
                        for sub in sub_entries.flatten() {
                            let sp = sub.path();
                            if sp.extension().is_some_and(|e| e == "pdb") {
                                pdb_paths.push(sp);
                            }
                        }
                    }
                } else if path.extension().is_some_and(|e| e == "pdb") {
                    pdb_paths.push(path);
                }

                for pdb_path in &pdb_paths {
                    if let Ok(content) = fs::read_to_string(pdb_path) {
                        let mut current_res: Option<(String, String)> = None;
                        let mut current_atoms: Vec<(String, u64)> = Vec::new();

                        for line in content.lines() {
                            if !line.starts_with("HETATM") && !line.starts_with("ATOM  ") {
                                continue;
                            }
                            if line.len() < 54 {
                                continue;
                            }

                            let atom_name = line.get(12..16).unwrap_or("").trim();
                            let res_name = line.get(17..20).unwrap_or("").trim();
                            let res_num = line.get(22..26).unwrap_or("").trim();
                            let serial_str = line.get(6..11).unwrap_or("").trim();

                            if !sugar_residues.contains(&res_name) {
                                continue;
                            }
                            if !ring_atom_names.contains(&atom_name) {
                                continue;
                            }

                            let this_res = (res_name.to_string(), res_num.to_string());

                            if current_res.as_ref() != Some(&this_res) {
                                // Save previous residue if complete
                                if current_atoms.len() >= 5
                                    && let Some(ref cr) = current_res
                                {
                                    all_residues.push((
                                        cr.0.clone(),
                                        cr.1.clone(),
                                        current_atoms.clone(),
                                    ));
                                }
                                current_res = Some(this_res);
                                current_atoms.clear();
                            }

                            if let Ok(serial) = serial_str.parse::<u64>()
                                && !current_atoms.iter().any(|(n, _)| n == atom_name)
                            {
                                current_atoms.push((atom_name.to_string(), serial));
                            }
                        }

                        // Don't forget the last residue
                        if current_atoms.len() >= 5
                            && let Some(ref cr) = current_res
                        {
                            all_residues.push((cr.0.clone(), cr.1.clone(), current_atoms));
                        }
                    }
                }
            }
        }
        if !all_residues.is_empty() {
            break;
        }
    }

    all_residues
}

fn default_atom_names() -> Vec<String> {
    ["C1", "C2", "C3", "C4", "C5", "O5"]
        .iter()
        .map(std::string::ToString::to_string)
        .collect()
}

fn default_residue_filters() -> Vec<String> {
    ["XYS", "BXYL", "BXY", "GLC", "GAL", "MAN", "FUC", "XYL"]
        .iter()
        .map(std::string::ToString::to_string)
        .collect()
}

/// Parse a GROMACS .gro file to extract atom indices using profile-driven
/// atom names and residue filters. Falls back to carbohydrate ring defaults.
fn extract_ring_atoms_from_gro(
    path: &Path,
    atom_names: &[String],
    residue_filters: &[String],
) -> Option<RingAtoms> {
    let content = std::fs::read_to_string(path).ok()?;
    let lines: Vec<&str> = content.lines().collect();

    if lines.len() < 3 {
        return None;
    }

    let mut found: Vec<(String, usize)> = Vec::new();

    for (line_pos, line) in lines[2..].iter().enumerate() {
        let atom_idx = line_pos + 1;
        if line.len() < 20 {
            continue;
        }

        let res_name = line.get(5..10).unwrap_or("").trim();
        let atom_name = line.get(10..15).unwrap_or("").trim();

        if residue_filters.iter().any(|s| res_name == s.as_str())
            && atom_names.iter().any(|a| atom_name == a.as_str())
            && !found.iter().any(|(n, _)| n == atom_name)
        {
            found.push((atom_name.to_string(), atom_idx));
        }
    }

    if found.is_empty() { None } else { Some(found) }
}
