// SPDX-License-Identifier: AGPL-3.0-or-later

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use super::scope;

pub(super) fn generate_validation_stub(name: &str, version: &str) -> String {
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    format!(
        r#"{{
  "artifact": "{name}",
  "version": "{version}",
  "date": "{date}",
  "modules": [],
  "summary": {{
    "modules_total": 0,
    "modules_pass": 0,
    "modules_in_flight": 0
  }}
}}
"#
    )
}

pub(super) fn generate_ferment_stub(name: &str, version: &str, origin: &str) -> String {
    let spring = origin.split('/').next_back().unwrap_or("unknown");
    let timestamp = chrono::Utc::now().to_rfc3339();
    format!(
        r#"{{
  "dataset_id": "{name}_v{version}",
  "spring": "{spring}",
  "spring_version": "{version}",
  "braid_id": "braid-{name}-{version}",
  "timestamp": "{timestamp}",
  "computation": {{}}
}}
"#
    )
}

pub(super) fn generate_readme(
    name: &str,
    version: &str,
    origin: &str,
    profile: Option<&pseudospore_core::DomainProfile>,
    data_dir: Option<&Path>,
    configs_dir: Option<&Path>,
) -> String {
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();

    // Build module list from data directory
    let modules = data_dir
        .map(|d| {
            let mut mods = Vec::new();
            if let Ok(entries) = std::fs::read_dir(d) {
                for e in entries.flatten() {
                    if e.path().is_dir() {
                        mods.push(e.file_name().to_string_lossy().to_string());
                    }
                }
            }
            mods.sort();
            mods
        })
        .unwrap_or_default();

    let total_ns: u64 = configs_dir.map_or(0, |c| {
        modules
            .iter()
            .filter_map(|m| scope::find_mdp_and_extract_time(&c.join(m)))
            .sum()
    });

    // Science summary: domain-agnostic template. Specific content comes from the
    // domain_profile.toml or is populated manually after emission.
    let science_summary = if let Some(p) = profile {
        format!(
            "pseudoSpore generated by {} domain profile (v{})",
            p.id, p.version
        )
    } else {
        String::new()
    };
    let key_finding = "";
    let paper_ref = "";

    // Module table
    let mut module_table = String::new();
    for m in &modules {
        let (system, cv, _method) = scope::infer_module_metadata(m, profile);
        let ns = configs_dir.and_then(|c| scope::find_mdp_and_extract_time(&c.join(m)));
        let _ = writeln!(
            module_table,
            "| `{m}` | {system} | {cv} | {} ns |",
            ns.unwrap_or(0)
        );
    }

    format!(
        r"# {name} v{version}

{science_summary}

**Key finding:** {key_finding}

**Paper:** {paper_ref}

---

## Quick Start

| Want to... | Look at... |
|-----------|------------|
| See the results visually | `figures/` — publication-quality FEL plots |
| Understand atom numbering | `TRANSLATE.md` — PDB↔GROMACS index mapping with derivation commands |
| Verify data integrity | `./validate` — runs airgapped with just `b3sum` (or `litho` if available) |
| Reproduce the FES | `plumed sum_hills --hills data/<module>/HILLS --outfile fes.dat --mintozero` |
| Load the crystal structure | `data/2D24.pdb` — GH10 xylanase with bound β-D-xylopyranose |
| Read the machine-readable claims | `validation.json` — per-module scientific assertions with numbers |
| Refresh data from source | `./refresh` — re-fetches datasets, reports hash changes |

## Modules ({n_modules} simulations, {total_ns} ns total)

| Module | System | CV | Time |
|--------|--------|----|----- |
{module_table}
## File Inventory

| Item | What it is |
|------|-----------|
| `figures/` | Publication-quality FEL plots (1D comparison + 2D heatmaps) |
| `data/` | Raw simulation data — HILLS deposits, topology (.gro), crystal structure (.pdb) |
| `outputs/` | Derived results — free energy surfaces (fes_theta.dat, fes_2d.dat) |
| `configs/` | GROMACS MDP + PLUMED input files to reproduce each simulation |
| `provenance/` | Lineage chain — ferment transcript + braid files tracing artifact history |
| `receipts/` | Integrity proof — BLAKE3 checksums + environment snapshot |
| `scope.toml` | Identity document — modules, paper DOI, simulation times, license |
| `validation.json` | Scientific claims — per-module pass/fail with specific numeric assertions |
| `domain_profile.toml` | Machine-readable domain specification (audit/emit/promote logic) |
| `index_map.toml` | Atom index translation table (PDB serial ↔ GROMACS line position) |
| `TRANSLATE.md` | Human-readable atom mapping + derivation commands |
| `data.toml` | Data manifest — source URIs, licenses, BLAKE3 hashes, refresh commands |
| `tolerances.toml` | Named numeric tolerances with scientific justification |
| `liveSpore.json` | Deployment log — records each successful validation run |
| `validate` | Entry point — verify integrity airgapped (exit 0=pass, 1=fail, 2=partial) |
| `refresh` | Data freshness — re-fetch from sources, report hash deltas |
| `README.md` | This file |

## Verification

```bash
# Quickest (needs only b3sum):
./validate

# Full audit (needs litho CLI):
litho audit --path . --verbose

# Structured JSON report:
litho audit --path . --json
```

## For Agents

This artifact is fully machine-parseable. Start with `scope.toml` (TOML) for module
inventory, `validation.json` (JSON) for scientific claims, and `data.toml` (TOML) for
dataset provenance. The `domain_profile.toml` declares all domain-specific logic for
automated audit, emit, and promote operations. Run `litho audit --path . --json` for
a structured validation report.

---

**Date:** {date} | **Origin:** {origin} | **License:** AGPL-3.0-or-later
",
        n_modules = modules.len(),
    )
}

pub(super) fn generate_translate_stub() -> String {
    r"# Translation: Domain ↔ Computation

## Atom Indices

See `index_map.toml` for the machine-readable mapping.

| Ring atom | Domain (PDB serial) | Computation (runtime index) |
|-----------|--------------------|-----------------------------|
| ... | ... | ... |

Rosetta stone: `data/<module>/npt.gro` (topology file)

## Conventions

| | Domain standard | This artifact |
|--|----------------|---------------|
| Numbering | PDB serial | Runtime topology (mapped in index_map.toml) |
| Checksums | — | BLAKE3 |

## Derivations

| Output | Data | Command |
|--------|------|---------|
| `outputs/<module>/...` | `data/<module>/...` | `<tool> <args>` |
"
    .to_string()
}

/// Generate validate and refresh entry point scripts.
pub(super) fn generate_entry_scripts(root: &Path, name: &str, version: &str) -> Result<(), String> {
    let validate_sh = format!(
        r#"#!/bin/bash
set -euo pipefail
# validate — guideStone entry point for {name} v{version}
# Runs airgapped; no network or NUCLEUS required.
# Exit: 0=PASS, 1=FAIL, 2=partial (Tier 3 unavailable)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== pseudoSpore validate: {name} v{version} ==="
echo

# Check if litho is available (bundled or PATH)
if [[ -x "./runtime/bin/litho" ]]; then
    LITHO="./runtime/bin/litho"
elif command -v litho &>/dev/null; then
    LITHO="litho"
else
    echo "WARN: litho CLI not found; falling back to BLAKE3 check only"
    if command -v b3sum &>/dev/null; then
        echo "[1] Verifying BLAKE3 checksums..."
        b3sum --check receipts/checksums.blake3 && echo "  PASS" || exit 1
    else
        echo "ERROR: neither litho nor b3sum available"
        exit 1
    fi
    exit 2
fi

# Run full audit
START_MS=$(($(date +%s%N)/1000000))
if [[ "${{1:-}}" == "--json" ]]; then
    "$LITHO" audit --path . --json
else
    "$LITHO" audit --path . --verbose
fi
RESULT=$?
END_MS=$(($(date +%s%N)/1000000))
RUNTIME=$((END_MS - START_MS))

# Append to liveSpore.json on success
if [[ $RESULT -eq 0 && -f liveSpore.json ]]; then
    HOSTNAME_HASH=$(echo -n "$(hostname)" | b3sum --no-names 2>/dev/null || echo "unknown")
    ARCH=$(uname -m)
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

    MODULES_TOTAL=$(find data/ -maxdepth 1 -type d | tail -n +2 | wc -l)
    python3 -c "
import json, sys
entry = {{
    'timestamp': '$TIMESTAMP',
    'hostname_hash': '$HOSTNAME_HASH',
    'arch': '$ARCH',
    'os': '$OS',
    'tier_reached': 2,
    'modules_passed': $MODULES_TOTAL,
    'modules_total': $MODULES_TOTAL,
    'runtime_ms': $RUNTIME
}}
with open('liveSpore.json', 'r') as f:
    data = json.load(f)
# Unified schema: {{envelope, validations}}
if isinstance(data, dict) and 'validations' in data:
    data['validations'].append(entry)
elif isinstance(data, list):
    data = {{'envelope': {{}}, 'validations': data + [entry]}}
else:
    data = {{'envelope': data, 'validations': [entry]}}
with open('liveSpore.json', 'w') as f:
    json.dump(data, f, indent=2)
" 2>/dev/null || true
fi

exit $RESULT
"#
    );

    let refresh_header = format!(
        "#!/bin/bash\nset -euo pipefail\n# refresh — data freshness protocol for {name} v{version}\n\nSCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\ncd \"$SCRIPT_DIR\"\n\necho \"=== pseudoSpore refresh: {name} v{version} ===\"\necho\n"
    );
    let refresh_body = r#"
if [[ ! -f data.toml ]]; then
    echo "ERROR: data.toml not found"
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 required for data.toml parsing"
    exit 1
fi

python3 << 'PYEOF'
import subprocess, os, sys

try:
    import tomllib
except ImportError:
    import tomli as tomllib

with open('data.toml', 'rb') as f:
    manifest = tomllib.load(f)

datasets = manifest.get('dataset', [])
changed = 0
total = 0

for ds in datasets:
    ds_id = ds.get('id', '?')
    local = ds.get('local_path', '')
    old_hash = ds.get('blake3', '')
    refresh = ds.get('refresh_command', '')
    total += 1

    if refresh.startswith('#') or not refresh.strip():
        print(f'  [{ds_id}] SKIP (manual refresh required)')
        continue

    print(f'  [{ds_id}] Refreshing from source...', end=' ')
    result = subprocess.run(refresh, shell=True, capture_output=True)
    if result.returncode != 0:
        print('FAILED')
        continue

    # Re-hash with b3sum fallback
    if os.path.isdir(local):
        result2 = subprocess.run(['b3sum', '--no-names'] + sorted(
            os.path.join(r, f) for r, _, fs in os.walk(local) for f in fs
        ), capture_output=True, text=True)
        new_hash = result2.stdout.strip().split('\n')[-1] if result2.returncode == 0 else 'error'
    elif os.path.isfile(local):
        result2 = subprocess.run(['b3sum', '--no-names', local], capture_output=True, text=True)
        new_hash = result2.stdout.strip() if result2.returncode == 0 else 'error'
    else:
        print('MISSING')
        continue

    if new_hash == old_hash:
        print('UNCHANGED')
    else:
        print(f'CHANGED (was {old_hash[:12]}... now {new_hash[:12]}...)')
        changed += 1

print()
print(f'=== Refresh complete: {total} datasets, {changed} changed ===')
if changed > 0:
    print('  Re-run ./validate to verify with updated data')
    print('  Update data.toml blake3 hashes if refresh is permanent')
PYEOF
"#;
    let refresh_sh = format!("{refresh_header}{refresh_body}");

    fs::write(root.join("validate"), validate_sh).map_err(|e| format!("emit: {e}"))?;
    fs::write(root.join("refresh"), refresh_sh).map_err(|e| format!("emit: {e}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        fs::set_permissions(root.join("validate"), perms.clone()).ok();
        fs::set_permissions(root.join("refresh"), perms).ok();
    }
    Ok(())
}
