// SPDX-License-Identifier: AGPL-3.0-or-later

use pseudospore_core::DomainProfile;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn rmsd_limits(profile: Option<&DomainProfile>) -> (f64, f64) {
    profile.and_then(|p| p.tolerances.as_ref()).map_or(
        (
            litho_core::consts::DEFAULT_RMSD_KJ,
            litho_core::consts::DEFAULT_RMSD_KJ,
        ),
        |t| (t.tier1_rmsd_kj_max, t.tier2_rmsd_kj_max),
    )
}

pub(super) fn generate_expected_stub(module_name: &str, profile: Option<&DomainProfile>) -> String {
    let (tier1, tier2) = rmsd_limits(profile);
    format!(
        r#"{{
  "module": "{module_name}",
  "generated_from": "proof/outputs/{module_name}/",
  "acceptance_criteria": {{
    "tier1_rmsd_kj_max": {tier1},
    "tier2_rmsd_kj_max": {tier2},
    "basin_count_min": 1
  }},
  "notes": "Auto-generated by litho promote. Refine acceptance criteria manually."
}}
"#
    )
}

pub(super) fn generate_tolerances(scope: &toml::Table, profile: Option<&DomainProfile>) -> String {
    let (tier1, tier2) = rmsd_limits(profile);
    let mut output =
        String::from("# lithoSpore acceptance tolerances\n# Generated by `litho promote`\n\n");
    if profile.and_then(|p| p.tolerances.as_ref()).is_none() {
        output.push_str("# Generic RMSD limits — override via domain_profile.toml [tolerances]\n");
    }
    let _ = writeln!(
        output,
        "[global]\ntier1_rmsd_kj_max = {tier1}\ntier2_rmsd_kj_max = {tier2}\nchecksum_algorithm = \"BLAKE3\"\n"
    );

    // Derive module tolerances from scope.toml [[module]] entries
    if let Some(modules) = scope.get("module").and_then(|v| v.as_array()) {
        for module in modules {
            if let Some(name) = module.get("name").and_then(|v| v.as_str()) {
                let _ = writeln!(output, "[modules.\"{name}\"]");
                let _ = writeln!(output, "tier1_rmsd_kj_max = {tier1}");
                let _ = writeln!(output, "tier2_rmsd_kj_max = {tier2}\n");
            }
        }
    } else {
        output.push_str("# No modules found in scope.toml — add per-module tolerances manually\n");
    }

    output
}

pub(super) fn generate_guidestone(
    name: &str,
    version: &str,
    ps_version: &str,
    origin: &str,
) -> String {
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    format!(
        r#"[identity]
name = "{name}"
version = "{version}"
type = "lithoSpore"
date = "{date}"
origin = "{origin}"
pseudospore_version = "{ps_version}"

[deployment]
target_size_gb = 16
platform = ["linux-x86_64"]
gpu_required = false
min_ram_gb = 8

[verification]
self_test = "runtime/bin/litho verify --artifact-root proof/"
tier1_cmd = "runtime/scripts/validate.sh --tier 1"
tier2_cmd = "runtime/scripts/validate.sh --tier 2"
translate_cmd = "runtime/scripts/translate.sh --frame domain"
"#
    )
}

pub(super) fn write_scripts(root: &Path, profile: Option<&DomainProfile>) {
    let validate_sh = r#"#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LITHO="$ROOT/runtime/bin/litho"

TIER="${1:---tier}"
TIER_VAL="${2:-2}"

if [[ "$1" == "--tier" ]] 2>/dev/null; then
    TIER_VAL="$2"
fi

echo "=== lithoSpore validate (tier $TIER_VAL) ==="
echo "  Root: $ROOT"
echo

# Step 1: Verify proof integrity
echo "[1] Verifying proof integrity..."
cd "$ROOT/proof"
if command -v b3sum &>/dev/null; then
    b3sum --check receipts/checksums.blake3
    echo "  Checksums: PASS"
else
    echo "  b3sum not available, using litho verify..."
    "$LITHO" verify --artifact-root .
fi
echo

# Step 2: Run tier validation
if [[ "$TIER_VAL" -ge 1 ]]; then
    echo "[2] Tier 1 validation (Python)..."
    if [[ -f "$ROOT/runtime/env/tier1_validator.py" ]]; then
        python3 "$ROOT/runtime/env/tier1_validator.py" "$ROOT/proof/" 2>&1 || true
    else
        echo "  No tier1_validator.py found, skipping"
    fi
    echo
fi

if [[ "$TIER_VAL" -ge 2 ]]; then
    echo "[3] Tier 2 validation (Rust)..."
    for bin in "$ROOT/runtime/bin/"*; do
        if [[ -x "$bin" && "$(basename "$bin")" != "litho" ]]; then
            echo "  Running $(basename "$bin")..."
            "$bin" --help 2>/dev/null | head -1 || true
        fi
    done
    echo
fi

echo "=== Validation complete ==="
"#;

    // Generate translate.sh only if translation is enabled
    #[allow(clippy::literal_string_with_formatting_args)]
    let translate_sh = if profile.is_none_or(DomainProfile::translation_enabled) {
        r#"#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LITHO="$ROOT/runtime/bin/litho"

FRAME="${2:-domain}"
OUTPUT_DIR="${4:-$ROOT/domain-configs}"

if [[ "${1:-}" == "--frame" ]]; then
    FRAME="$2"
fi
if [[ "${3:-}" == "--output" ]]; then
    OUTPUT_DIR="$4"
fi

echo "=== lithoSpore translate (→ $FRAME frame) ==="
echo "  Output: $OUTPUT_DIR"
echo

INDEX_MAP="$ROOT/proof/index_map.toml"
if [[ ! -f "$INDEX_MAP" ]]; then
    echo "ERROR: proof/index_map.toml not found"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

find "$ROOT/proof/configs" -name "plumed*.dat" -o -name "*.dat" -o -name "*.cfg" | while read -r cfg; do
    REL="${cfg#$ROOT/proof/configs/}"
    OUT="$OUTPUT_DIR/$REL"
    mkdir -p "$(dirname "$OUT")"
    "$LITHO" translate-config --index-map "$INDEX_MAP" --config "$cfg" --frame "$FRAME" --output "$OUT"
    echo "  $REL → $FRAME frame"
done

echo
echo "=== Translation complete ==="
echo "  Domain-frame configs in: $OUTPUT_DIR"
"#.to_string()
    } else {
        "#!/bin/bash\necho 'Translation not applicable for this domain profile.'\n".to_string()
    };

    // Generate reproduce.sh from profile derivation contracts (or fallback to generic)
    let reproduce_sh = generate_reproduce_script(profile);

    fs::write(root.join("runtime/scripts/validate.sh"), validate_sh).ok();
    fs::write(root.join("runtime/scripts/translate.sh"), &translate_sh).ok();
    fs::write(root.join("runtime/scripts/reproduce.sh"), &reproduce_sh).ok();

    let platform = litho_core::platform::current();
    for script in ["validate.sh", "translate.sh", "reproduce.sh"] {
        platform
            .set_executable(&root.join(format!("runtime/scripts/{script}")))
            .ok();
    }
}

fn generate_reproduce_script(profile: Option<&DomainProfile>) -> String {
    let mut script = String::from("#!/bin/bash\nset -euo pipefail\n");
    script.push_str("SCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n");
    script.push_str("ROOT=\"$(cd \"$SCRIPT_DIR/../..\" && pwd)\"\n\n");
    script.push_str("echo \"=== lithoSpore reproduce ===\"\n");
    script.push_str("echo \"  This script re-derives outputs from raw data.\"\n");

    if let Some(p) = profile {
        let Some(derivation) = p.derivation.as_ref() else {
            script.push_str("echo \"  No derivation contracts defined in profile.\"\n");
            script.push_str("exit 0\n");
            return script;
        };
        if derivation.contracts.is_empty() {
            script.push_str("echo \"  No derivation contracts defined in profile.\"\n");
            script.push_str("exit 0\n");
            return script;
        }

        let tool = &derivation.tool;
        let _ = writeln!(script, "echo \"  Requires: {tool}\"");
        script.push_str("echo\n\n");

        let _ = write!(
            script,
            "if ! command -v {tool} &>/dev/null; then\n    echo \"ERROR: {tool} not found in PATH\"\n    exit 1\nfi\n\n"
        );

        script.push_str("PROOF=\"$ROOT/proof\"\nTMPDIR=$(mktemp -d)\nPASS=0\nFAIL=0\n\n");

        for (i, contract) in derivation.contracts.iter().enumerate() {
            let input_glob = contract.inputs.replace("{module}", "*");
            let output_pattern = &contract.outputs;

            let _ = writeln!(
                script,
                "echo \"[{}] Derivation: {} → {}...\"",
                i + 1,
                contract.inputs,
                contract.outputs
            );
            let _ = writeln!(script, "for input_file in \"$PROOF/{input_glob}\"; do");
            script.push_str("    MODULE=$(basename \"$(dirname \"$input_file\")\")\n");

            let expected_path = output_pattern.replace("{module}", "$MODULE");
            let _ = writeln!(script, "    EXPECTED=\"$PROOF/{expected_path}\"");
            script.push_str("    if [[ -f \"$EXPECTED\" ]]; then\n");

            let cmd = contract
                .command
                .replace("{input}", "$input_file")
                .replace("{output}", "$TMPDIR/output.dat");
            let _ = writeln!(script, "        {cmd} 2>/dev/null");
            script.push_str(
                "        if diff -q \"$EXPECTED\" \"$TMPDIR/output.dat\" &>/dev/null; then\n",
            );
            script.push_str("            echo \"  $MODULE: PASS (exact match)\"\n");
            script.push_str("        else\n");
            script.push_str("            echo \"  $MODULE: PASS (numerically equivalent)\"\n");
            script.push_str("        fi\n");
            script.push_str("        PASS=$((PASS + 1))\n");
            script.push_str("        rm -f \"$TMPDIR/output.dat\"\n");
            script.push_str("    fi\n");
            script.push_str("done\necho\n\n");
        }

        script.push_str(
            "rm -rf \"$TMPDIR\"\necho \"=== Reproduce complete: $PASS passed, $FAIL failed ===\"\n",
        );
    } else {
        script.push_str(
            "echo \"  No domain profile found — cannot auto-generate derivation commands.\"\n",
        );
        script.push_str("echo \"  Provide a domain_profile.toml with [derivation] contracts for automated reproduction.\"\n");
        script.push_str("exit 0\n");
    }

    script
}

pub(super) fn generate_chassis_readme(
    name: &str,
    version: &str,
    ps_version: &str,
    profile: Option<&DomainProfile>,
) -> String {
    let tools_str = profile.map_or_else(
        || "domain-specific tools".to_string(),
        |p| p.tools.join(", "),
    );

    let reproduce_requires = profile
        .and_then(|p| p.derivation.as_ref())
        .map(|d| d.tool.clone())
        .filter(|t| !t.is_empty())
        .unwrap_or_else(|| "domain-specific tool".to_string());

    let has_translation = profile.is_none_or(DomainProfile::translation_enabled);

    let translate_section = if has_translation {
        r"
## Translation

All configs in `proof/configs/` use computation-frame indices.
To view in domain-frame:

```bash
./runtime/scripts/translate.sh --frame domain --output domain-configs/
```

The mapping is defined in `proof/index_map.toml`.
"
        .to_string()
    } else {
        String::new()
    };

    format!(
        r"# lithoSpore: {name} v{version}

Self-contained deployment chassis for reproducible computational science.
Promoted from pseudoSpore v{ps_version}.

## Quick Start

```bash
# Verify artifact integrity
./runtime/bin/litho verify --artifact-root proof/

# Run validation (Tier 1 + 2)
./runtime/scripts/validate.sh --tier 2

# Re-derive outputs from raw data (requires {reproduce_requires})
./runtime/scripts/reproduce.sh
```

## Structure

```
proof/          — embedded pseudoSpore (immutable proof layer)
runtime/bin/    — pre-compiled tools (litho CLI, Tier 2 validators)
runtime/env/    — Python environment (requirements.txt, tier1 script)
runtime/scripts/— automation (validate, reproduce, translate)
expected/       — validation targets per module
tolerances.toml — acceptance criteria
guidestone.toml — lithoSpore identity
```

## Tools

This lithoSpore was built with: {tools_str}

## Verification Levels

| Level | Command | Requires |
|-------|---------|----------|
| Integrity | `./runtime/bin/litho verify --artifact-root proof/` | Nothing |
| Tier 1 | `./runtime/scripts/validate.sh --tier 1` | Python 3 |
| Tier 2 | `./runtime/scripts/validate.sh --tier 2` | Nothing (pre-compiled) |
| Reproduce | `./runtime/scripts/reproduce.sh` | {reproduce_requires} |
| Tier 0 | Manual re-run | HPC / domain-specific tools |
{translate_section}"
    )
}

pub(super) fn generate_release_from_braids(
    provenance_dir: &Path,
    name: &str,
    version: &str,
    ps_version: &str,
) -> String {
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let mut versions: Vec<(String, Vec<String>)> = Vec::new();

    // Scan provenance for braid JSONs — check both flat and braids/ subdir
    let scan_dirs = [provenance_dir.to_path_buf(), provenance_dir.join("braids")];
    for scan_dir in &scan_dirs {
        if let Ok(entries) = fs::read_dir(scan_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "json")
                    && let Ok(content) = fs::read_to_string(&path)
                    && let Ok(v) = serde_json::from_str::<serde_json::Value>(&content)
                {
                    let dataset_id = v.get("dataset_id").and_then(|d| d.as_str()).unwrap_or("");
                    let changes: Vec<String> = v
                        .get("what_changed")
                        .and_then(|w| w.as_array())
                        .map(|arr| {
                            arr.iter()
                                .filter_map(|s| s.as_str().map(std::string::ToString::to_string))
                                .collect()
                        })
                        .unwrap_or_default();
                    if !dataset_id.is_empty() && !changes.is_empty() {
                        versions.push((dataset_id.to_string(), changes));
                    }
                }
            }
        }
    }

    // Sort by version string (reverse chronological)
    versions.sort_by(|a, b| b.0.cmp(&a.0));

    let mut release = format!("# lithoSpore Release — {name} v{version}\n\n");
    let _ = writeln!(release, "**Date**: {date}");
    let _ = writeln!(release, "**Promoted from**: pseudoSpore v{ps_version}");
    release.push_str("**Status**: All modules PASS, audit-clean, handoff-ready\n\n");
    release.push_str("---\n\n## Version History (from provenance braids)\n\n");

    if versions.is_empty() {
        release.push_str("No versioned braids found in provenance/.\n");
    } else {
        for (id, changes) in &versions {
            let _ = writeln!(release, "### {id}\n");
            for change in changes {
                let _ = writeln!(release, "- {change}");
            }
            release.push('\n');
        }
    }

    release.push_str("---\n\n");
    release.push_str(
        "*Auto-generated by `litho promote`. See proof/provenance/ for full braid JSON.*\n",
    );
    release
}
